// Generated by Hive CE
// Do not modify
// Check in to version control

import 'package:hive_ce/hive_ce.dart';
import 'package:fylorg/data/models/move_log_entry.dart';
import 'package:fylorg/data/models/organize_rule.dart';

extension HiveRegistrar on HiveInterface {
  void registerAdapters() {
    registerAdapter(MoveLogEntryAdapter());
    registerAdapter(OrganizeRuleAdapter());
  }
}

extension IsolatedHiveRegistrar on IsolatedHiveInterface {
  void registerAdapters() {
    registerAdapter(MoveLogEntryAdapter());
    registerAdapter(OrganizeRuleAdapter());
  }
}
